# Generated by Django 3.2.6 on 2021-11-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_source',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
