# Generated by Django 3.2.6 on 2021-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_source',
            field=models.CharField(default='NONE', max_length=600),
        ),
    ]
