# Generated by Django 3.2.6 on 2021-11-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_image_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_source',
        ),
    ]
