# Generated by Django 3.2.6 on 2021-11-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_product_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_source',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
